#!/bin/bash
# Fix TOC entries to match new shortened headings
DIR="/Users/yc/YCBookBlog/docs/07.计算机/04.数据库原理"

# Helper: replace TOC line in a file
toc_fix() {
  local f="$1"; local old="$2"; local new="$3"
  # Fix display text in TOC (the first [text] part)
  sed -i '' "s/- \\[$old\\](/- [$new](/" "$f"
  # Fix the anchor part too if it changed
  local old_anchor=$(echo "$old" | sed 's/ /-/g; s/——/-/g; s/—/-/g; s/→/-/g')
  local new_anchor=$(echo "$new" | sed 's/ /-/g; s/——/-/g; s/—/-/g; s/→/-/g')
  if [ "$old_anchor" != "$new_anchor" ]; then
    sed -i '' "s/\\(#$old_anchor\\)/(#$new_anchor)/g" "$f"
  fi
}
# Same but for sub-entries (indented with spaces)
toc_fix_sub() {
  local f="$1"; local old="$2"; local new="$3"
  sed -i '' "s/- \\[$old\\](/- [$new](/" "$f"
}

# === File 02 ===
F="$DIR/02.索引底层原理.md"
# Section headings
toc_fix "$F" "1.1 一个慢查询差点拖垮订单系统" "1.1 慢查询拖垮订单"
toc_fix "$F" "1.2 为什么学了SQL还要学索引原理" "1.2 为何学索引原理"
toc_fix "$F" "2.3 索引设计的核心权衡" "2.3 索引核心权衡"
toc_fix "$F" "03.二分查找与二叉搜索树" "03.二分与二叉"
toc_fix "$F" "4.2 为什么是B+Tree而不是B-Tree" "4.2 B vs B+"
toc_fix "$F" "4.3 为什么比红黑树更适合磁盘" "4.3 对比红黑树"
toc_fix "$F" "4.6 页分裂——最贵的操作" "4.6 页分裂"
toc_fix "$F" "4.7 B+Tree的删除与页合并" "4.7 删除与页合并"
toc_fix "$F" "05.聚簇索引与二级索引" "05.两种索引"
toc_fix "$F" "5.1 聚簇索引——数据即索引" "5.1 聚簇索引"
toc_fix "$F" "5.2 二级索引——需要回表" "5.2 二级索引"
toc_fix "$F" "5.4 为什么建议用自增主键" "5.4 自增主键"
toc_fix "$F" "06.联合索引与最左前缀" "06.联合索引"
toc_fix "$F" "6.1 联合索引的物理结构" "6.1 联合索引结构"
toc_fix "$F" "6.3 范围查询断点效应" "6.3 范围断点"
toc_fix "$F" "6.4 索引字段顺序的设计原则" "6.4 字段顺序原则"
toc_fix "$F" "07.覆盖索引与索引下推" "07.覆盖与下推"
toc_fix "$F" "7.1 覆盖索引——不回表的优化" "7.1 覆盖索引"
toc_fix "$F" "8.1 Hash索引的极致速度" "8.1 Hash速度"
toc_fix "$F" "8.2 Hash索引的致命缺陷" "8.2 Hash缺陷"
toc_fix "$F" "8.3 InnoDB自适应哈希索引" "8.3 自适应Hash"
toc_fix "$F" "09.索引失效的十大场景" "09.索引失效"
toc_fix "$F" "9.1 函数与运算导致失效" "9.1 函数与运算"
toc_fix "$F" "9.3 模糊查询左模糊" "9.3 左模糊"
toc_fix "$F" "10.2 优化器的选错与纠正" "10.2 选错纠正"
toc_fix "$F" "11.综合案例订单表索引优化" "11.综合案例"

# === File 03 ===
F="$DIR/03.事务与隔离级别.md"
toc_fix "$F" "1.1 一次线上事故——库存超卖" "1.1 库存超卖"
toc_fix "$F" "1.2 为什么要学事务原理" "1.2 为何学事务原理"
toc_fix "$F" "2.3 MySQL中如何开启事务" "2.3 开启事务"
toc_fix "$F" "3.1 原子性Atomicity" "3.1 原子性"
toc_fix "$F" "3.2 一致性Consistency" "3.2 一致性"
toc_fix "$F" "3.3 隔离性Isolation" "3.3 隔离性"
toc_fix "$F" "3.4 持久性Durability" "3.4 持久性"
toc_fix "$F" "3.5 ACID的实现机制总览" "3.5 实现总览"
toc_fix "$F" "4.1 脏读Dirty Read" "4.1 脏读"
toc_fix "$F" "4.2 不可重复读Non-Repeatable Read" "4.2 不可重复读"
toc_fix "$F" "4.3 幻读Phantom Read" "4.3 幻读"
toc_fix "$F" "4.4 丢失更新Lost Update" "4.4 丢失更新"
toc_fix "$F" "4.5 四种问题对比总结" "4.5 对比总结"
toc_fix "$F" "5.1 SQL标准定义的隔离级别" "5.1 隔离级别定义"
toc_fix "$F" "5.2 READ UNCOMMITTED 读未提交" "5.2 读未提交"
toc_fix "$F" "5.3 READ COMMITTED 读已提交" "5.3 读已提交"
toc_fix "$F" "5.4 REPEATABLE READ 可重复读" "5.4 可重复读"
toc_fix "$F" "5.5 SERIALIZABLE 串行化" "5.5 串行化"
toc_fix "$F" "5.6 InnoDB下RR的特殊表现" "5.6 RR特殊表现"
toc_fix "$F" "6.1 MVCC的核心思想" "6.1 MVCC思想"
toc_fix "$F" "6.2 隐藏列与undo log" "6.2 隐藏列与undo"
toc_fix "$F" "6.3 Read View——事务的快照" "6.3 Read View"
toc_fix "$F" "6.4 RC下的Read View" "6.4 RC下ReadView"
toc_fix "$F" "6.5 RR下的Read View" "6.5 RR下ReadView"
toc_fix "$F" "6.6 为什么RR能部分防幻读" "6.6 部分防幻读"
toc_fix "$F" "07.Undo Log——MVCC的基石" "07.Undo Log"
toc_fix "$F" "7.1 Undo Log的结构" "7.1 Undo结构"
toc_fix "$F" "7.2 Undo Log的版本链" "7.2 版本链"
toc_fix "$F" "7.3 Undo Log的清理——purge线程" "7.3 purge清理"
toc_fix "$F" "7.4 长事务为什么是灾难" "7.4 长事务灾难"
toc_fix "$F" "08.隔离级别的选择" "08.隔离级别选择"
toc_fix "$F" "8.1 隔离级别与并发性能的权衡" "8.1 性能权衡"
toc_fix "$F" "8.2 不同场景的选型建议" "8.2 选型建议"
toc_fix "$F" "8.3 查看与修改隔离级别" "8.3 查看与修改"
toc_fix "$F" "09.综合案例秒杀系统的库存扣减" "09.综合案例"
toc_fix "$F" "9.1 场景与问题分析" "9.1 场景分析"
toc_fix "$F" "9.2 五种方案对比" "9.2 方案对比"
toc_fix "$F" "9.3 知识图谱回顾" "9.3 知识图谱"

# === File 04 ===
F="$DIR/04.锁机制详解.md"
toc_fix "$F" "1.1 一次死锁事故——秒杀系统的瘫痪" "1.1 秒杀死锁"
toc_fix "$F" "1.2 为什么要深入学锁原理" "1.2 为何学锁原理"
toc_fix "$F" "2.2 锁与事务隔离级别的关系" "2.2 锁与隔离级别"
toc_fix "$F" "2.3 快照读 vs 当前读——谁用锁" "2.3 快照读vs当前读"
toc_fix "$F" "03.锁的粒度——全局/表/页/行" "03.锁的粒度"
toc_fix "$F" "4.1 S锁与X锁的兼容矩阵" "4.1 兼容矩阵"
toc_fix "$F" "4.3 索引与锁——没有索引会怎样" "4.3 索引与锁"
toc_fix "$F" "5.1 Record Lock——记录锁" "5.1 记录锁"
toc_fix "$F" "5.2 Gap Lock——间隙锁" "5.2 间隙锁"
toc_fix "$F" "5.3 Next-Key Lock——临键锁" "5.3 临键锁"
toc_fix "$F" "5.4 为什么RR下默认用Next-Key Lock" "5.4 RR下临键锁"
toc_fix "$F" "06.意向锁——表锁与行锁的桥梁" "06.意向锁"
toc_fix "$F" "6.1 为什么需要意向锁" "6.1 为何意向锁"
toc_fix "$F" "6.2 IS/IX锁的兼容性" "6.2 锁兼容性"
toc_fix "$F" "07.自增锁Auto-Inc Lock" "07.自增锁"
toc_fix "$F" "7.1 AUTO_INCREMENT的并发问题" "7.1 自增并发"
toc_fix "$F" "7.2 三种自增锁模式" "7.2 自增模式"
toc_fix "$F" "08.一条UPDATE到底加了哪些锁" "08.UPDATE加锁"
toc_fix "$F" "8.1 等值查询——唯一索引命中" "8.1 唯一索引等值"
toc_fix "$F" "8.2 等值查询——普通索引命中" "8.2 普通索引等值"
toc_fix "$F" "9.1 死锁的四个必要条件" "9.1 死锁条件"
toc_fix "$F" "9.2 死锁复现——两个事务互相等待" "9.2 死锁复现"
toc_fix "$F" "9.3 死锁检测与解除" "9.3 检测与解除"
toc_fix "$F" "9.4 死锁日志解读" "9.4 日志解读"
toc_fix "$F" "9.5 如何避免死锁" "9.5 避免死锁"
toc_fix "$F" "10.综合案例秒杀系统的锁优化" "10.综合案例"
toc_fix "$F" "10.2 方案对比与知识图谱" "10.2 方案对比"

# === File 05 ===
F="$DIR/05.存储引擎对比.md"
toc_fix "$F" "1.1 Buffer Pool 太小引发的血案" "1.1 BP过小血案"
toc_fix "$F" "1.2 为什么要深入存储引擎" "1.2 为何学引擎"
toc_fix "$F" "2.1 存储引擎的职责" "2.1 引擎职责"
toc_fix "$F" "2.2 MySQL的插件式引擎架构" "2.2 插件式架构"
toc_fix "$F" "2.3 为什么InnoDB是默认引擎" "2.3 为何是InnoDB"
toc_fix "$F" "3.1 表空间的五层结构" "3.1 五层结构"
toc_fix "$F" "3.2 表空间文件详解" "3.2 文件详解"
toc_fix "$F" "3.3 段Segment和区Extent" "3.3 段和区"
toc_fix "$F" "4.1 16KB页的完整布局" "4.1 页布局"
toc_fix "$F" "4.2 页目录——页内二分查找" "4.2 页目录"
toc_fix "$F" "4.3 记录格式——COMPACT与REDUNDANT" "4.3 记录格式"
toc_fix "$F" "4.4 行溢出与BLOB页" "4.4 行溢出"
toc_fix "$F" "05.Buffer Pool——InnoDB的心脏" "05.Buffer Pool"
toc_fix "$F" "5.1 Buffer Pool的三大链表" "5.1 三大链表"
toc_fix "$F" "5.2 冷热分离的LRU" "5.2 冷热分离LRU"
toc_fix "$F" "5.5 Buffer Pool的预热" "5.5 BP预热"
toc_fix "$F" "5.6 多实例Buffer Pool" "5.6 多实例BP"
toc_fix "$F" "06.Change Buffer——写入加速器" "06.Change Buffer"
toc_fix "$F" "6.2 Change Buffer vs 直接写磁盘" "6.2 vs直接写盘"
toc_fix "$F" "6.3 Change Buffer的适用场景" "6.3 适用场景"
toc_fix "$F" "07.Double Write Buffer" "07.DoubleWrite"
toc_fix "$F" "7.1 为什么需要Double Write" "7.1 为何需要"
toc_fix "$F" "7.2 Double Write的工作流程" "7.2 工作流程"
toc_fix "$F" "08.自适应哈希索引" "08.自适应Hash"
toc_fix "$F" "8.1 AHI的工作原理" "8.1 AHI原理"
toc_fix "$F" "8.2 AHI的开关与监控" "8.2 开关与监控"
toc_fix "$F" "9.1 八大维度对比" "9.1 维度对比"
toc_fix "$F" "9.2 为什么MyISAM的COUNT快" "9.2 COUNT快"
toc_fix "$F" "9.3 什么时候选MyISAM" "9.3 何时MyISAM"
toc_fix "$F" "10.3 MySQL 8.0引擎新格局" "10.3 8.0新格局"
toc_fix "$F" "11.综合案例大促前的Buffer Pool调优" "11.综合案例"
toc_fix "$F" "11.2 调优方案与效果" "11.2 方案与效果"
toc_fix "$F" "11.3 知识图谱回顾" "11.3 知识图谱"

# === File 06 ===
F="$DIR/06.SQL查询优化.md"
toc_fix "$F" "1.1 首页加载5秒——一条SQL引发的血案" "1.1 首页加载5秒"
toc_fix "$F" "1.2 为什么要学查询优化" "1.2 为何学优化"
toc_fix "$F" "02.EXPLAIN深度解读" "02.EXPLAIN解读"
toc_fix "$F" "2.2 id——表的执行顺序" "2.2 执行顺序"
toc_fix "$F" "2.3 select_type——查询类型" "2.3 查询类型"
toc_fix "$F" "2.4 type——访问类型（最重要的字段）" "2.4 访问类型"
toc_fix "$F" "2.5 possible_keys与key——选了什么索引" "2.5 选了何索引"
toc_fix "$F" "2.6 key_len——用了索引的多少字节" "2.6 索引字节"
toc_fix "$F" "2.7 rows——估算扫描行数" "2.7 扫描行数"
toc_fix "$F" "2.8 Extra——额外信息（第二重要的字段）" "2.8 额外信息"
toc_fix "$F" "2.9 EXPLAIN FORMAT=JSON——更精确的信息" "2.9 JSON格式"
toc_fix "$F" "3.2 mysqldumpslow分析工具" "3.2 慢查询工具"
toc_fix "$F" "3.3 pt-query-digest——慢查询之王" "3.3 慢查询之王"
toc_fix "$F" "04.SQL优化实战——索引篇" "04.索引优化"
toc_fix "$F" "4.1 索引失效的排查清单" "4.1 失效清单"
toc_fix "$F" "4.3 ORDER BY与GROUP BY优化" "4.3 排序分组优化"
toc_fix "$F" "05.SQL优化实战——改写篇" "05.改写优化"
toc_fix "$F" "5.1 LIMIT 大偏移量优化" "5.1 大偏移量"
toc_fix "$F" "5.4 分页查询的正确姿势" "5.4 分页姿势"
toc_fix "$F" "5.5 多值INSERT——批量写入加速" "5.5 批量写入"
toc_fix "$F" "06.查询优化器追踪" "06.优化器追踪"
toc_fix "$F" "6.1 Optimizer Trace——为什么选了全表扫描" "6.1 选全表原因"
toc_fix "$F" "6.2 强制索引的边界" "6.2 强制索引"
toc_fix "$F" "07.综合案例多表关联订单查询优化" "07.综合案例"
toc_fix "$F" "7.1 场景与原始SQL" "7.1 原始SQL"
toc_fix "$F" "7.2 优化全流程" "7.2 优化流程"

# === File 07 ===
F="$DIR/07.日志系统设计.md"
toc_fix "$F" "1.1 一次崩溃后数据丢了" "1.1 崩溃丢数据"
toc_fix "$F" "1.2 为什么要学日志系统" "1.2 为何学日志"
toc_fix "$F" "2.1 redo log / undo log / binlog 的职责" "2.1 三种日志职责"
toc_fix "$F" "2.2 三种日志的对比" "2.2 日志对比"
toc_fix "$F" "2.3 日志写在什么位置" "2.3 日志位置"
toc_fix "$F" "3.1 为什么先写日志再写数据" "3.1 为何WAL"
toc_fix "$F" "3.2 WAL的全流程" "3.2 WAL流程"
toc_fix "$F" "3.3 WAL的性能优势" "3.3 WAL优势"
toc_fix "$F" "04.Redo Log——持久性的守护者" "04.Redo Log"
toc_fix "$F" "4.1 Redo Log的结构" "4.1 Redo结构"
toc_fix "$F" "4.2 Redo Log的写入流程" "4.2 Redo写入"
toc_fix "$F" "4.3 Redo Log的循环写入" "4.3 循环写入"
toc_fix "$F" "4.4 Checkpoint机制" "4.4 检查点"
toc_fix "$F" "4.5 组提交Group Commit" "4.5 组提交"
toc_fix "$F" "4.6 Redo Log的三层缓冲区" "4.6 三层缓冲"
toc_fix "$F" "05.Binlog——主从复制的基石" "05.Binlog"
toc_fix "$F" "5.1 Binlog的三种格式" "5.1 三种格式"
toc_fix "$F" "5.2 Binlog的写入时机——两阶段提交" "5.2 两阶段提交"
toc_fix "$F" "5.3 Binlog vs Redo Log" "5.3 对比Redo"
toc_fix "$F" "06.Undo Log回顾" "06.Undo Log"
toc_fix "$F" "6.1 Undo Log的双重使命" "6.1 双重使命"
toc_fix "$F" "6.2 三种日志协同完成一次UPDATE" "6.2 一次UPDATE"
toc_fix "$F" "7.1 恢复的总流程" "7.1 恢复流程"
toc_fix "$F" "7.2 Redo Log重放——已提交的必须恢复" "7.2 Redo重放"
toc_fix "$F" "7.3 Undo Log回滚——未提交的必须撤销" "7.3 Undo回滚"
toc_fix "$F" "7.4 三种崩溃场景分析" "7.4 崩溃场景"
toc_fix "$F" "08.综合案例机房断电后的恢复" "08.综合案例"

# === File 08 ===
F="$DIR/08.主从复制架构.md"
toc_fix "$F" "1.1 一次主从延迟引发的线上事故" "1.1 主从延迟事故"
toc_fix "$F" "1.2 为什么要深入复制原理" "1.2 为何学复制"
toc_fix "$F" "2.3 Binlog Dump协议——数据如何从主库流向从库" "2.3 Dump协议"
toc_fix "$F" "03.异步复制——基础模型" "03.异步复制"
toc_fix "$F" "3.2 异步复制的问题——主从延迟与数据丢失" "3.2 延迟与丢失"
toc_fix "$F" "3.3 主从延迟的量化和监控" "3.3 延迟监控"
toc_fix "$F" "3.4 Relay Log的结构与Crash-Safe" "3.4 Relay Log"
toc_fix "$F" "3.5 复制过滤——不是所有数据都值得同步" "3.5 复制过滤"
toc_fix "$F" "4.1 AFTER_SYNC vs AFTER_COMMIT" "4.1 同步模式对比"
toc_fix "$F" "4.2 半同步复制的退级机制" "4.2 退级机制"
toc_fix "$F" "05.GTID——全局事务标识" "05.GTID"
toc_fix "$F" "5.1 为什么需要GTID" "5.1 为何GTID"
toc_fix "$F" "5.2 GTID的组成" "5.2 GTID组成"
toc_fix "$F" "5.3 GTID模式下的主从切换" "5.3 主从切换"
toc_fix "$F" "5.4 GTID的生命周期" "5.4 生命周期"
toc_fix "$F" "5.5 GTID的三大限制与陷阱" "5.5 限制与陷阱"
toc_fix "$F" "5.6 GTID模式下从库的自动恢复" "5.6 自动恢复"
toc_fix "$F" "6.1 单线程SQL的瓶颈" "6.1 SQL瓶颈"
toc_fix "$F" "6.2 基于组的并行复制LOGICAL_CLOCK" "6.2 并行复制"
toc_fix "$F" "6.3 并行复制的三种模式" "6.3 三种模式"
toc_fix "$F" "6.4 WRITESET——并行复制的终极形态" "6.4 WRITESET"
toc_fix "$F" "07.读写分离与延迟处理" "07.读写分离"
toc_fix "$F" "7.2 主从延迟的应对策略" "7.2 延迟策略"
toc_fix "$F" "7.3 级联复制——解耦主库的传输压力" "7.3 级联复制"
toc_fix "$F" "7.4 延迟从库——误操作的最后防线" "7.4 延迟从库"
toc_fix "$F" "8.1 MHA自动故障转移" "8.1 MHA"
toc_fix "$F" "8.2 Orchestrator自动拓扑管理" "8.2 拓扑管理"
toc_fix "$F" "8.3 InnoDB Cluster / Group Replication" "8.3 MGR"
toc_fix "$F" "09.综合案例大促主从延迟优化" "09.综合案例"
toc_fix "$F" "9.2 优化方案与效果" "9.2 优化效果"
toc_fix "$F" "9.3 知识图谱回顾" "9.3 知识图谱"
toc_fix "$F" "9.4 探索——多源复制的架构" "9.4 多源复制"

# === File 09 ===
F="$DIR/09.分库分表方案.md"
toc_fix "$F" "1.1 一张订单表撑爆了数据库" "1.1 订单表撑爆"
toc_fix "$F" "1.2 为什么要学分库分表" "1.2 为何学分库分表"
toc_fix "$F" "2.1 垂直拆分 vs 水平拆分" "2.1 垂直vs水平"
toc_fix "$F" "2.2 分库 vs 分表" "2.2 分库vs分表"
toc_fix "$F" "3.1 垂直分库——按业务拆分" "3.1 垂直分库"
toc_fix "$F" "3.2 垂直分表——冷热分离" "3.2 垂直分表"
toc_fix "$F" "3.3 垂直拆分的代价" "3.3 拆分代价"
toc_fix "$F" "4.1 水平分库+分表" "4.1 水平分库表"
toc_fix "$F" "4.2 分片键的选择" "4.2 选分片键"
toc_fix "$F" "4.4 基因法——解决非分片键查询" "4.4 基因法"
toc_fix "$F" "4.5 冗余索引表方案" "4.5 冗余索引表"
toc_fix "$F" "5.1 分片键查询——精准路由" "5.1 精准路由"
toc_fix "$F" "5.2 非分片键查询——全分片广播" "5.2 全分片广播"
toc_fix "$F" "5.3 分页查询——深度分页难题" "5.3 深度分页"
toc_fix "$F" "5.5 跨分片 JOIN" "5.5 跨分片JOIN"
toc_fix "$F" "6.1 为什么不能自增ID" "6.1 不能自增"
toc_fix "$F" "6.2 雪花算法Snowflake" "6.2 雪花算法"
toc_fix "$F" "7.2 双写迁移——零停机" "7.2 双写迁移"
toc_fix "$F" "7.3 分片扩容——数据重分布" "7.3 分片扩容"
toc_fix "$F" "8.1 代理模式 vs 客户端模式" "8.1 代理vs客户端"
toc_fix "$F" "09.综合案例亿级订单表拆分" "09.综合案例"
toc_fix "$F" "9.1 场景与方案设计" "9.1 方案设计"
toc_fix "$F" "9.2 迁移全流程" "9.2 迁移流程"
toc_fix "$F" "9.3 知识图谱回顾" "9.3 知识图谱"

# === File 10 ===
F="$DIR/10.NoSQL设计思想.md"
toc_fix "$F" "1.1 热点数据击垮了MySQL" "1.1 热点击垮MySQL"
toc_fix "$F" "1.2 为什么要学NoSQL" "1.2 为何学NoSQL"
toc_fix "$F" "2.1 为什么需要NoSQL" "2.1 为何NoSQL"
toc_fix "$F" "3.1 为什么Redis这么快" "3.1 为何快"
toc_fix "$F" "3.2 五种基本数据结构" "3.2 基本结构"
toc_fix "$F" "3.3 三种高级数据结构" "3.3 高级结构"
toc_fix "$F" "3.4 底层编码——一个类型多种实现" "3.4 底层编码"
toc_fix "$F" "3.5 Redis字典与渐进式Rehash" "3.5 渐进Rehash"
toc_fix "$F" "3.6 Redis事务与Pipeline" "3.6 事务Pipeline"
toc_fix "$F" "04.Redis持久化——内存数据库的可靠性" "04.持久化"
toc_fix "$F" "4.3 RDB + AOF 混合持久化" "4.3 混合持久化"
toc_fix "$F" "4.4 COW原理深度解析" "4.4 COW原理"
toc_fix "$F" "4.5 AOF重写机制的深层原理" "4.5 AOF重写"
toc_fix "$F" "05.Redis淘汰策略与过期机制" "05.淘汰策略"
toc_fix "$F" "5.1 过期删除策略" "5.1 过期删除"
toc_fix "$F" "5.2 内存淘汰策略" "5.2 内存淘汰"
toc_fix "$F" "5.3 淘汰策略的选择" "5.3 策略选择"
toc_fix "$F" "5.4 近似LRU的采样淘汰池" "5.4 采样淘汰池"
toc_fix "$F" "06.Redis高可用——哨兵与集群" "06.高可用"
toc_fix "$F" "6.4 Gossip协议与节点通信" "6.4 Gossip协议"
toc_fix "$F" "6.5 Redis Stream与消费者组" "6.5 Stream"
toc_fix "$F" "07.NoSQL vs SQL——选型决策" "07.选型决策"
toc_fix "$F" "7.1 五种场景的选择" "7.1 五种场景"
toc_fix "$F" "7.2 多级缓存架构" "7.2 多级缓存"
toc_fix "$F" "7.3 缓存三大问题" "7.3 三大问题"
toc_fix "$F" "08.MongoDB与Elasticsearch速览" "08.Mongo与ES"
toc_fix "$F" "8.1 MongoDB——文档数据库" "8.1 MongoDB"
toc_fix "$F" "8.2 Elasticsearch——搜索引擎" "8.2 ES搜索引擎"
toc_fix "$F" "8.3 WiredTiger存储引擎原理" "8.3 WiredTiger"
toc_fix "$F" "8.4 ES的分片与段合并机制" "8.4 ES分片合并"
toc_fix "$F" "09.综合案例秒杀系统的多级缓存" "09.综合案例"
toc_fix "$F" "9.1 场景与设计" "9.1 场景设计"
toc_fix "$F" "9.2 知识图谱回顾" "9.2 知识图谱"

echo "All TOC entries fixed"
